base = float(input())
brutto_bonus = round(base * 100 / 86, -1)
income_tax = round(brutto_bonus / 100 * 13, 2)
pension_contribution = round(brutto_bonus /100 * 35, 2)
insurance_fee = round(brutto_bonus /100 * 0.6, 2)
netto_bonus = brutto_bonus - income_tax - brutto_bonus /100 * 1
print("Премия", brutto_bonus)
print("Подоходный налог", income_tax)
print ("ФСЗН", pension_contribution)
print("Белгосстрах", insurance_fee)
print("К выплате", netto_bonus)
